COMMON: &common
  SECRET_KEY: insecure
  SECURITY_POST_LOGIN_VIEW: '/profile'
  SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@127.0.0.1:5432/xsama_flask_social
  ADMIN_CREDENTIALS: 'admin,admin'

  SECURITY_TRACKABLE: True
  SOCIAL_CONNECT_ALLOW_VIEW: '/profile'

  SOCIAL_TWITTER:
    consumer_key: 'key'
    consumer_secret: 'secret'

  SOCIAL_FACEBOOK:
    consumer_key: 'key'
    consumer_secret: 'secret'
    request_token_params:
      scope: 'email,publish_stream'

  SOCIAL_GITHUB:
    consumer_key: 'key'
    consumer_secret: 'secret'
    module: 'app.github'

DEVELOPMENT: &development
  <<: *common
  DEBUG: True

PRODUCTION: &production
  <<: *common
  DEBUG: True
  SECURITY_PASSWORD_HASH: bcrypt
  SOCIAL_APP_URL: http://xsama.com/
